// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAY8YOrgk9VjhpYzbAVdsdjDUP6FCFJWDc',
    appId: '1:714784057945:web:0bd5f937f20b622a64df48',
    messagingSenderId: '714784057945',
    projectId: 'lakshya-ac3d9',
    authDomain: 'lakshya-ac3d9.firebaseapp.com',
    databaseURL: 'https://lakshya-ac3d9-default-rtdb.firebaseio.com',
    storageBucket: 'lakshya-ac3d9.appspot.com',
    measurementId: 'G-FFTSRN1Q4E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCT7e_HjZ8_qZ1H-SvWaErSjsQ6oi3KfWY',
    appId: '1:714784057945:android:39c16661c99f762764df48',
    messagingSenderId: '714784057945',
    projectId: 'lakshya-ac3d9',
    databaseURL: 'https://lakshya-ac3d9-default-rtdb.firebaseio.com',
    storageBucket: 'lakshya-ac3d9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCuLxrK13S3-72FQoUnSXLy-DT7U1EduIQ',
    appId: '1:714784057945:ios:4725532be6723fac64df48',
    messagingSenderId: '714784057945',
    projectId: 'lakshya-ac3d9',
    databaseURL: 'https://lakshya-ac3d9-default-rtdb.firebaseio.com',
    storageBucket: 'lakshya-ac3d9.appspot.com',
    androidClientId: '714784057945-1h5vvrj2ojfrdnlm0p5va08hbhghg13e.apps.googleusercontent.com',
    iosBundleId: 'com.example.turfuser',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCuLxrK13S3-72FQoUnSXLy-DT7U1EduIQ',
    appId: '1:714784057945:ios:4725532be6723fac64df48',
    messagingSenderId: '714784057945',
    projectId: 'lakshya-ac3d9',
    databaseURL: 'https://lakshya-ac3d9-default-rtdb.firebaseio.com',
    storageBucket: 'lakshya-ac3d9.appspot.com',
    androidClientId: '714784057945-1h5vvrj2ojfrdnlm0p5va08hbhghg13e.apps.googleusercontent.com',
    iosBundleId: 'com.example.turfuser',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAY8YOrgk9VjhpYzbAVdsdjDUP6FCFJWDc',
    appId: '1:714784057945:web:5f73104250702b2564df48',
    messagingSenderId: '714784057945',
    projectId: 'lakshya-ac3d9',
    authDomain: 'lakshya-ac3d9.firebaseapp.com',
    databaseURL: 'https://lakshya-ac3d9-default-rtdb.firebaseio.com',
    storageBucket: 'lakshya-ac3d9.appspot.com',
    measurementId: 'G-Q2DCB46YLF',
  );
}
